In [1]:
import numpy as np

In [4]:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [7]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [8]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [10]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.random.rand(1)

array([0.41346455])

In [15]:
np.random.randn(25)

array([ 0.67177442, -0.91870252,  2.36223606,  0.74249226, -0.40973346,
        2.16371838, -0.15006248, -0.56665437,  1.14208578,  0.60700313,
       -0.63439278, -0.2038062 , -0.25842397,  0.52129283,  0.40419104,
        0.54317734,  0.09148903,  0.00571891, -2.50265111,  0.6311887 ,
       -0.47052837, -0.79392074, -0.51682372, -0.03541888,  1.0083926 ])

In [24]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [25]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [32]:
np.arange(1,26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [41]:
import numpy as np
a=np.arange(1,26).reshape(5,5)
a[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [42]:
import numpy as np
a=np.arange(1,26).reshape(5,5)
a[1:,2:]

array([[ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20],
       [23, 24, 25]])

In [46]:
a[3:4,4:]

array([[20]])

In [55]:
a[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [56]:
a[4:]

array([[21, 22, 23, 24, 25]])

In [61]:
a[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [63]:
a.sum()#sum of all matrix

325

In [64]:
a.std()#standard deviation 

7.211102550927978

In [65]:
sum(a)

array([55, 60, 65, 70, 75])

In [66]:
a.sum(axis=0)#sum of colums

array([55, 60, 65, 70, 75])

In [67]:
a.sum(axis=1)#sum of rows

array([ 15,  40,  65,  90, 115])

In [94]:
a=np.arange(4)
a

array([0, 1, 2, 3])

In [92]:
b=np.arange(4).reshape(2,2)
b

array([[0, 1],
       [2, 3]])

In [79]:
b

array([[0, 1],
       [2, 3]])

In [88]:
c=np.arange(1,13).reshape(3,2,2)
c

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [3]:
import numpy as np
c=np.arange(1,5).reshape(2,2)
c

array([[1, 2],
       [3, 4]])

In [81]:
b.dtype

dtype('int32')

In [90]:
c.shape

(3, 2, 2)

In [4]:
c.ndim

2

In [95]:
a.shape

(4,)

In [84]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [86]:
np.ones(4).reshape(2,2)

array([[1., 1.],
       [1., 1.]])

In [5]:
maths_marks=np.random.randint(1,100,20)
maths_marks

array([79, 93, 87, 59, 81, 93, 38, 20, 51, 53, 41, 32, 22, 85, 44, 78, 60,
        1, 15,  5])

In [6]:
np.sort(maths_marks)

array([ 1,  5, 15, 20, 22, 32, 38, 41, 44, 51, 53, 59, 60, 78, 79, 81, 85,
       87, 93, 93])

In [7]:
asc=2, 11, 23, 30, 41, 47, 53, 54, 58, 66, 76, 78, 80, 84, 85, 87, 88, 89, 92, 99
np.flip(asc)

array([99, 92, 89, 88, 87, 85, 84, 80, 78, 76, 66, 58, 54, 53, 47, 41, 30,
       23, 11,  2])

In [8]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
np.eye(5,5).reshape(25)

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [10]:
np.eye(5,5).ravel()

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [11]:
np.eye(5,5).flatten()

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [12]:
mat=np.arange(0,9).reshape(3,3)
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
np.append(mat,[[9,10,11]],axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [14]:
x=np.arange(0,9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
np.split(x,3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [16]:
v=mat
v

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
np.split(v,3,axis=1)

[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]

In [18]:
np.eye(4)+4

array([[5., 4., 4., 4.],
       [4., 5., 4., 4.],
       [4., 4., 5., 4.],
       [4., 4., 4., 5.]])

In [19]:
s=np.random.uniform(0,9,10)
s

array([3.48314707, 3.8741277 , 5.48020292, 2.25162101, 6.2043053 ,
       7.63739563, 8.84041602, 4.57287791, 4.79553008, 3.85369336])

In [20]:
np.ceil(s)

array([4., 4., 6., 3., 7., 8., 9., 5., 5., 4.])

In [21]:
np.floor(s)

array([3., 3., 5., 2., 6., 7., 8., 4., 4., 3.])

In [22]:
np.round(s,decimals=2)

array([3.48, 3.87, 5.48, 2.25, 6.2 , 7.64, 8.84, 4.57, 4.8 , 3.85])

In [23]:
h=np.arange(0,25).reshape(5,5)
h

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
h.min(axis=0)

array([0, 1, 2, 3, 4])

In [25]:
h.max(axis=0)

array([20, 21, 22, 23, 24])

In [26]:
h.var(axis=0)

array([50., 50., 50., 50., 50.])

In [27]:
h.std(axis=0)

array([7.07106781, 7.07106781, 7.07106781, 7.07106781, 7.07106781])

In [28]:
mv=np.arange(100,151)
mv

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [29]:
np.flip(mv)

array([150, 149, 148, 147, 146, 145, 144, 143, 142, 141, 140, 139, 138,
       137, 136, 135, 134, 133, 132, 131, 130, 129, 128, 127, 126, 125,
       124, 123, 122, 121, 120, 119, 118, 117, 116, 115, 114, 113, 112,
       111, 110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100])

In [30]:
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
dh=np.array([1,2,3,4,5])
dh

array([1, 2, 3, 4, 5])

In [32]:
hd=(1,0,2,0,0,4,0,8)
hd

(1, 0, 2, 0, 0, 4, 0, 8)

In [33]:
np.nonzero(hd)

(array([0, 2, 5, 7], dtype=int64),)

In [34]:
z=np.ones((10,10))
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [35]:
z[1:9,1:9]=0
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [36]:
p=np.zeros((8,8),dtype=int)
p[::2,::2]=1
p[1::2,1::2]=1
p

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [ ]:
# create a 5x5 matrix of 7's  split it row ,column, dimmensuin, shape, datatype, add one column 

In [40]:
a=np.ones(25)*7
a

array([7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.,
       7., 7., 7., 7., 7., 7., 7., 7.])

In [42]:
a.reshape(5,5)

array([[7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.]])

In [44]:
a.shape

(25,)

In [45]:
a.ndim

1

In [46]:
a.dtype

dtype('float64')

In [2]:
import numpy as np
np.vsplit(a,5)

NameError: name 'a' is not defined